apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: database
data:
  aws_access_key_id: QUtJQVZSVVZRNkZUNUVGSFVWSEc=
  aws_secret_access_key: azBLcWpHS2dVbkN2UWlZMGdvVEJ0ekZYUU1LV3h4WXZ3cWR3MnpleQ==


