apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      nodePort: 30000  # NodePort can be any available port in the range 30000-32767
    - name: agent-port
      port: 50000
      targetPort: 50000
      nodePort: 30001  # This is the port Jenkins agents will use to connect
  selector:
    app: jenkins

