apiVersion: batch/v1
kind: CronJob
metadata:
  name: jenkins-backup-cronjob
  namespace: jenkins
spec:
  schedule: "*/5 * * * *"  # Adjust as needed
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: another-service-account
          containers:
          - name: jenkins-backup
            image: my-local-image:latest
            imagePullPolicy: Never
            command: ["/bin/sh", "-c"]
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            args: ["/usr/local/bin/backup-script.sh"]
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: jenkins-backup-config

