apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/jenkins/pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: jenkins-pv2

