apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "list"]  # Ensure 'get' and 'list' are included
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: another-service-account
  namespace: jenkins
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

